"""create initial certificate schema

Revision ID: ed0045394361
Revises: 
Create Date: 2026-09-11 13:59:29.131221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0045394361'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('cpe_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('issuance_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issuance_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('signing_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('certificates',
    sa.Column('certificate_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('participant_hash', sa.String(length=71), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='valid', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['signing_keys.key_id'], ),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('event_id', 'participant_hash', name='uq_certificates_event_participant')
    )
    op.create_table('issuance_links',
    sa.Column('link_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=71), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issuance_links')
    op.drop_table('certificates')
    op.drop_table('signing_keys')
    op.drop_table('events')
    # ### end Alembic commands ###
